Repository matrip-project/matrip-server, pull requests merged in 2023-11, with the labels that each got.

#2 chore: swagger 의존성 추가
  build.gradle
  src/main/resources/application.yml
Labels: ⚙ Setting

#6 Feat/mt 47 동행 게시글 작성
  src/main/java/com/v1/matripserver/MatripServerApplication.java
  src/main/java/com/v1/matripserver/config/SecurityConfig.java
  src/main/java/com/v1/matripserver/journey/controller/JourneyController.java
  src/main/java/com/v1/matripserver/journey/dto/JourneyImgRequestDto.java
  src/main/java/com/v1/matripserver/journey/dto/JourneyRequestDto.java
  src/main/java/com/v1/matripserver/journey/dto/JourneyResponseDto.java
  src/main/java/com/v1/matripserver/journey/dto/PageRequestDTO.java
  src/main/java/com/v1/matripserver/journey/dto/PageResponseDTO.java
  src/main/java/com/v1/matripserver/journey/entity/Journey.java
  src/main/java/com/v1/matripserver/journey/entity/JourneyImg.java
  src/main/java/com/v1/matripserver/journey/repository/JourenyImgRepository.java
  src/main/java/com/v1/matripserver/journey/repository/JourneyRepository.java
  src/main/java/com/v1/matripserver/journey/service/JourneyService.java
Labels: 🔰BE, ✨ Feature

#9 Feat: 동행 필터링 및 검색
  src/main/java/com/v1/matripserver/journey/dto/PageRequestDTO.java
  src/main/java/com/v1/matripserver/journey/repository/JourneyRepository.java
  src/main/java/com/v1/matripserver/journey/service/JourneyService.java
Labels: 🔰BE, ✨ Feature

#11 fix: 전체 조회 시 필요한 데이터만 요청
  src/main/java/com/v1/matripserver/journey/controller/JourneyController.java
  src/main/java/com/v1/matripserver/journey/dto/JourneyResponseDto.java
  src/main/java/com/v1/matripserver/journey/entity/Journey.java
  src/main/java/com/v1/matripserver/journey/repository/JourneyRepository.java
  src/main/java/com/v1/matripserver/journey/service/JourneyService.java
Labels: 🔰BE, 🐞 BugFix

#13 Dev
  build.gradle
  src/main/java/com/v1/matripserver/auth/JwtTokenFilter.java
  src/main/java/com/v1/matripserver/auth/JwtTokenUtil.java
  src/main/java/com/v1/matripserver/auth/SessionListener.java
  src/main/java/com/v1/matripserver/config/SecurityConfig.java
  src/main/java/com/v1/matripserver/journey/controller/JourneyController.java
  src/main/java/com/v1/matripserver/journey/dto/JourneyResponseDto.java
  src/main/java/com/v1/matripserver/journey/entity/Journey.java
  src/main/java/com/v1/matripserver/journey/repository/JourneyRepository.java
  src/main/java/com/v1/matripserver/journey/service/JourneyService.java
  src/main/java/com/v1/matripserver/member/controller/MemberController.java
  src/main/java/com/v1/matripserver/member/dto/RequestDto.java
  src/main/java/com/v1/matripserver/member/service/MemberService.java
  src/main/java/com/v1/matripserver/member/service/MemberServiceImpl.java
  src/main/java/com/v1/matripserver/util/exceptions/BaseResponseStatus.java
Labels: 🔰BE, 🐞 BugFix, ✨ Feature

#15 !HotFix: SecurityConfig 순환 참조 오류 수정
  src/main/java/com/v1/matripserver/auth/JwtTokenFilter.java
  src/main/java/com/v1/matripserver/auth/PasswordEncoderConfig.java
  src/main/java/com/v1/matripserver/config/SecurityConfig.java
Labels: 🔰BE, 🐞 BugFix
